services:
  mysql:
    image: mysql:8.4
    ports:
      - "${DB_PORT}:3306"
    expose:
      - "${DB_PORT}"
    env_file:
      - .env
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"